# Análise Exploratória (EDA) - Pipeline Desafio Ray

## Estrutura
1. **Bronze Layer**: Dados brutos ingeridos
2. **Silver Layer**: Dados transformados e normalizados
3. Análises adicionais por necessidade

In [1]:
import pandas as pd

df_categoria_bronze = pd.read_parquet('../data/bronze/PS_Categoria.parquet')
df_cliente_bronze = pd.read_parquet('../data/bronze/PS_Cliente.parquet')
df_conta_pagamento_bronze = pd.read_parquet('../data/bronze/PS_Conta_Pagar.parquet')
df_conta_receber_bronze = pd.read_parquet('../data/bronze/PS_Conta_Receber.parquet')
df_meta_bronze = pd.read_parquet('../data/bronze/PS_Meta2025.parquet')
df_banco_central_bronze = pd.read_parquet('../data/bronze/bcb_cotacoes.parquet')

In [2]:
df_meta_silver = pd.read_parquet('../data/silver/meta_2025_silver.parquet')
df_categoria_silver = pd.read_parquet('../data/silver/categoria_silver.parquet')
df_cliente_silver = pd.read_parquet('../data/silver/cliente_silver.parquet')
df_conta_pagar_silver = pd.read_parquet('../data/silver/conta_pagar_silver.parquet')
df_conta_receber_silver = pd.read_parquet('../data/silver/conta_receber_silver.parquet')

## CATEGORIA

In [3]:
df_categoria_bronze.head()

  codigo_categoria                        nome_categoria tipo_categoria
0           1.1.01           VENDA DE PRODUTOS NACIONAIS        receita
1           1.1.02          VENDA DE PRODUTOS EXPORTAÇÃO        RECEITA
2           1.1.03       PRESTAÇÃO DE SERVIÇOS NACIONAIS        Receita
3           1.1.04  PRESTAÇÃO DE SERVIÇOS INTERNACIONAIS        reCeita
4           1.1.05                RECEITA DE ASSINATURAS        REceita

In [4]:
df_categoria_silver.head()

  codigo_categoria                        nome_categoria tipo_categoria
0           1.1.01           VENDA DE PRODUTOS NACIONAIS        RECEITA
1           1.1.02          VENDA DE PRODUTOS EXPORTACAO        RECEITA
2           1.1.03       PRESTACAO DE SERVICOS NACIONAIS        RECEITA
3           1.1.04  PRESTACAO DE SERVICOS INTERNACIONAIS        RECEITA
4           1.1.05                RECEITA DE ASSINATURAS        RECEITA

In [5]:
print(df_categoria_bronze.info())
print(df_categoria_bronze.value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   codigo_categoria  34 non-null     object
 1   nome_categoria    34 non-null     object
 2   tipo_categoria    34 non-null     object
dtypes: object(3)
memory usage: 972.0+ bytes
None
codigo_categoria  nome_categoria                            tipo_categoria
3.1.06            ÁGUA E SANEAMENTO                         despesa           2
1.1.02            VENDA DE PRODUTOS EXPORTAÇÃO              RECEITA           1
1.1.01            VENDA DE PRODUTOS NACIONAIS               receita           1
1.1.04            PRESTAÇÃO DE SERVIÇOS INTERNACIONAIS      reCeita           1
1.1.05            RECEITA DE ASSINATURAS                    REceita           1
1.1.06            RECEITA FINANCEIRA SOBRE APLICAÇÕES       receita           1
1.1.03            PRESTAÇÃO DE SERVIÇOS NACIONAIS           Receita           1
1.1.08            JUROS RECEBIDOS                           ReceitA           1
1.1.09            DIVIDENDOS RECEBIDOS                      receitA           1
1.1.10            RECEITA DE LICENCIAMENTO DE SOFTWARE      RECEita           1
3.1.01            SALÁRIOS E ORDENADOS                      despesa           1
3.1.02            ENCARGOS TRABALHISTAS                     DESPESA           1
3.1.03            IMPOSTOS E TAXAS                          Despesa           1
3.1.04            ALUGUEL E CONDOMÍNIO                      deSpesa           1
1.1.07            VARIAÇÃO CAMBIAL ATIVA                    RECEITA           1
3.1.05            ENERGIA ELÉTRICA                          DESpesa           1
3.1.07            INTERNET E TELECOMUNICAÇÕES               DESPESA           1
3.1.08            MARKETING E PUBLICIDADE                   DespESa           1
3.1.09            DESPESAS BANCÁRIAS INTERNACIONAIS         desPesA           1
3.1.10            TAXAS SOBRE OPERAÇÕES DE CÂMBIO           DESPesa           1
3.1.11            VARIAÇÃO CAMBIAL PASSIVA                  despESA           1
3.1.12            FRETES E LOGÍSTICA INTERNACIONAL          DESPESa           1
3.1.13            SOFTWARE / LICENÇA DE USO                 Despesa           1
3.1.14            CONSULTORIAS E SERVIÇOS TERCEIROS         dEspesa           1
3.1.15            SEGUROS EMPRESARIAIS                      DESpESA           1
3.1.16            MANUTENÇÃO DE SISTEMAS                    desPesa           1
3.1.17            INFRAESTRUTURA EM NUVEM                   DESPesa           1
3.1.18            CUSTOS COM API FINANCEIRA                 DespESa           1
3.1.19            TARIFAS DE TRANSFERÊNCIAS INTERNACIONAIS  despesa           1
3.1.20            PERDAS OPERACIONAIS                       DESPESA           1
3.1.21            OUTRAS DESPESAS OPERACIONAIS              despesa           1
Name: count, dtype: int64

## Cliente

In [6]:
df_cliente_bronze.head()

   id_cliente     nome_cliente    pais_cliente data_cadastro_cliente
0           1       Ana Souza           BRASIL            2023-01-05
1           2    CARLOS MENDES       portugal             12/01/2023
2           3   Julien  Martin         FranÃ§a            2023-01-18
3           4  michael johnson  Estados Unidos            25/01/2023
4           5     Sophia Brown         CANADÃ            2023-02-02

In [7]:
print(df_cliente_bronze.info())
print(df_cliente_bronze.value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_cliente             75 non-null     int64
 1   nome_cliente           75 non-null     object
 2   pais_cliente           75 non-null     object
 3   data_cadastro_cliente  75 non-null     object
dtypes: int64(1), object(3)
memory usage: 2.5+ KB
None
id_cliente  nome_cliente     pais_cliente    data_cadastro_cliente
1            Ana Souza       BRASIL          2023-01-05               1
2           CARLOS MENDES     portugal       12/01/2023               1
3           Julien  Martin   FranÃ§a         2023-01-18               1
4           michael johnson  Estados Unidos  25/01/2023               1
5            Sophia Brown    CANADÃ         2023-02-02               1
                                                                     ..
71          Amanda Ribeiro   BRASIL          2024-06-18               1
72          Francisco Neves   portugal       25/06/2024               1
73          Louis Mercier    FranÃ§a         2024-07-03               1
74          Daniel Brooks    ESTADOS UNIDOS  10/07/2024               1
75          Sarah Collins    CanadÃ¡         2024-07-18               1
Name: count, Length: 75, dtype: int64

## Metas

In [8]:
display(df_meta_bronze)

            mes_meta  meta
0            01/2025  700k
1            02/2025  650k
2      março de 2025  750k
3            04/2025  750k
4            05/2025  750k
5            06/2025  700k
6            07/2025  650k
7          ago./2025  750k
8            09/2025  800k
9            10/2025  700k
10           11/2025  700k
11  dezembro de 2025  700k

In [9]:
df_meta_bronze.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mes_meta  12 non-null     object
 1   meta      12 non-null     object
dtypes: object(2)
memory usage: 324.0+ bytes

In [10]:
df_meta_silver.head()

  mes_ano_meta  meta_valor  mes   ano   nome_mes
0   2025-01-01    700000.0    1  2025    janeiro
1   2025-02-01    650000.0    2  2025  fevereiro
2   2025-03-01    750000.0    3  2025      marco
3   2025-04-01    750000.0    4  2025      abril
4   2025-05-01    750000.0    5  2025       maio

## Banco

In [11]:
df_banco_central_bronze.head()

  moeda        data  cotacao_compra  cotacao_venda
0   CAD  2022-12-01          3.8667         3.8686
1   CAD  2022-12-02          3.8552         3.8568
2   CAD  2022-12-03          3.8552         3.8568
3   CAD  2022-12-04          3.8552         3.8568
4   CAD  2022-12-05          3.8802         3.8819

## Cliente

In [12]:
df_cliente_silver.head()

,id_cliente,nome_cliente,pais_cliente,moeda_pais,data_cadastro_cliente
0,1,Ana Souza,BRASIL,BRL,2023-01-05
1,2,Carlos Mendes,PORTUGAL,EUR,2023-01-12
2,3,Julien Martin,FRANCA,EUR,2023-01-18
3,4,Michael Johnson,ESTADOS UNIDOS,USD,2023-01-25
4,5,Sophia Brown,CANADA,CAD,2023-02-02

In [13]:
df_cliente_silver["pais_cliente"].value_counts()
# df_cliente_silver["moeda_pais"].value_counts()

pais_cliente
BRASIL            11
PORTUGAL          11
FRANCA            11
ESTADOS UNIDOS    11
CANADA            11
ARGENTINA         10
REINO UNIDO       10
Name: count, dtype: int64

## Contas a Pagar

In [14]:
df_conta_pagamento_bronze.head()

,id_conta,descricao_conta,destino_pagamento_conta,codigo_categoria,observacao_conta,valor_conta,data_vencimento,data_pagamento,status_conta
0,1,Aquisição de hardware,Limpeza & Brilho,3.1.06,None,5051.54,2025-05-09,2025-05-13,Pago
1,2,Assinatura mensal,Limpeza & Brilho,3.1.10,Vencimento em feriado,1673.39,2025-03-15,2025-03-11,Pago
2,3,Manutenção preventiva,Logística Rápida Ltda,3.1.02,Desconto aplicado,4309.58,2025-08-29,None,Em aberto
3,4,Licenciamento anual,Gráfica Rápida Express,3.1.05,Parcela 1/3,5398.39,2025-06-14,2025-06-16,Pago
4,5,Manutenção preventiva,Restaurante Sabor & Arte,3.1.17,Aguardando nota fiscal,7268.57,2025-04-12,None,Em aberto

In [15]:
df_conta_pagar_silver.head(10)

,id_conta,descricao_conta,destino_pagamento_conta,codigo_categoria,observacao_conta,valor_conta,valor_conta_brl,data_vencimento,data_pagamento,status_conta
0,1,Aquisição de hardware,Limpeza & Brilho,3.1.06,None,5051.54,5051.54,2025-05-09,2025-05-13,Pago
1,2,Assinatura mensal,Limpeza & Brilho,3.1.10,Vencimento em feriado,1673.39,1673.39,2025-03-15,2025-03-11,Pago
2,3,Manutenção preventiva,Logística Rápida Ltda,3.1.02,Desconto aplicado,4309.58,4309.58,2025-08-29,None,Em aberto
3,4,Licenciamento anual,Gráfica Rápida Express,3.1.05,Parcela 1/3,5398.39,5398.39,2025-06-14,2025-06-16,Pago
4,5,Manutenção preventiva,Restaurante Sabor & Arte,3.1.17,Aguardando nota fiscal,7268.57,7268.57,2025-04-12,None,Em aberto
5,6,Licenciamento anual,Marketing Criativo,3.1.02,Desconto aplicado,3561.35,3561.35,2025-12-25,None,Em aberto
6,7,Material de escritório,Seguros Global,3.1.06,None,5657.54,5657.54,2025-03-20,2025-03-25,Pago
7,8,Manutenção preventiva,Limpeza & Brilho,3.1.13,Urgente,4560.64,4560.64,2025-11-26,None,Atrasada
8,9,Licenciamento anual,Consultoria Alpha,3.1.16,Aprovação pendente,744.70,744.70,2025-01-23,None,Em aberto
9,10,Reparo emergencial,Gráfica Rápida Express,3.1.14,Aguardando nota fiscal,9129.08,9129.08,2025-01-27,2025-01-25,Pago

In [16]:
# print(df_conta_pagamento_bronze["descricao_conta"].value_counts())

df_conta_pagamento_bronze["destino_pagamento_conta"].value_counts()

destino_pagamento_conta
Auto Posto Petro                233
Restaurante Sabor & Arte        225
Energia Norte Distribuidora     222
Logística Rápida Ltda           220
Gráfica Rápida Express          218
Consultoria Alpha               215
Telecomunicações Connect        212
Seguros Global                  211
Papelaria Central               207
Manutenção Predial Silva        202
Limpeza & Brilho                202
Marketing Criativo              200
Tech Solutions S.A.             200
Transportadora Caminho Livre    200
Sistemas Integrados             199
Name: count, dtype: int64

## Contas a Receber

In [17]:
df_conta_receber_bronze.head()

,id_conta,descricao_conta,id_cliente,codigo_categoria,observacao_conta,valor_conta,data_vencimento,data_pagamento,status
0,1,Assinatura anual,73,1.1.05,Referente ao contrato Q4,39787.31,2025-09-27,2025-09-25,Pago
1,2,Recebimento de fatura,38,1.1.02,Aguardando transferência,216555.92,2025-05-12,None,Atrasado
2,3,Recebimento de fatura,52,1.1.06,Pagamento antecipado,8214.39,2025-04-17,2025-04-15,Pago
3,4,Recebimento de fatura,25,1.1.04,None,98459.91,2025-05-06,2025-05-02,Pago
4,5,Royalties,48,1.1.09,Bonificação incluída,236862.64,2025-01-20,None,Atrasado

In [18]:
df_conta_receber_silver.head(10)

,id_conta,descricao_conta,id_cliente,codigo_categoria,observacao_conta,valor_conta,valor_conta_brl,data_vencimento,data_pagamento,status_conta
0,1,Assinatura anual,73,1.1.05,Referente ao contrato Q4,39787.31,2.481455e+05,2025-09-27,2025-09-25,Pago
1,2,Recebimento de fatura,38,1.1.02,Aguardando transferência,216555.92,2.165559e+05,2025-05-12,None,Atrasado
2,3,Recebimento de fatura,52,1.1.06,Pagamento antecipado,8214.39,5.444498e+04,2025-04-17,2025-04-15,Pago
3,4,Recebimento de fatura,25,1.1.04,None,98459.91,5.552548e+05,2025-05-06,2025-05-02,Pago
4,5,Royalties,48,1.1.09,Bonificação incluída,236862.64,8.763918e+02,2025-01-20,None,Atrasado
5,6,Venda de produto,34,1.1.02,Referente ao contrato Q4,246511.73,9.120934e+02,2025-09-18,None,Em aberto
6,7,Mensalidade de serviço,43,1.1.06,Parcela única,14180.73,1.418073e+04,2025-04-03,2025-04-06,Pago
7,8,Comissão de vendas,41,1.1.06,None,75093.26,2.778451e+02,2025-10-04,None,Em aberto
8,9,Assinatura anual,11,1.1.09,None,246338.77,1.315572e+06,2025-12-04,2025-12-05,Pago
9,10,Projeto concluído,25,1.1.06,Pagamento antecipado,89169.41,8.916941e+04,2025-02-25,None,Atrasado

In [19]:
df_vencimentos_receber = df_conta_receber_bronze[["id_conta", "data_vencimento"]]
df_vencimentos_receber = df_vencimentos_receber["data_vencimento"].unique()

df_vencimentos_receber

array(['2025-09-27', '2025-05-12', '2025-04-17', '2025-05-06',
       '2025-01-20', '2025-09-18', '2025-04-03', '2025-10-04',
       '2025-12-04', '2025-02-25', '2025-05-23', '2025-02-09',
       '2025-09-26', '2025-12-07', '2025-01-16', '2025-05-01',
       '2025-11-11', '2025-06-25', '2025-11-20', '2025-06-06',
       '2025-09-23', '2025-03-08', '2025-08-16', '2025-05-08',
       '2025-01-21', '2025-09-17', '2025-06-15', '2025-11-16',
       '2025-02-26', '2025-07-02', '2025-03-31', '2025-11-10',
       '2025-06-03', '2025-12-12', '2025-04-06', '2025-12-28',
       '2025-06-17', '2025-08-20', '2025-04-15', '2025-12-27',
       '2025-09-14', '2025-12-23', '2025-04-22', '2025-06-10',
       '2025-04-29', '2025-05-24', '2025-10-20', '2025-10-26',
       '2025-10-19', '2025-05-19', '2025-05-21', '2025-03-21',
       '2025-06-12', '2025-05-26', '2025-01-07', '2025-02-13',
       '2025-03-06', '2025-02-19', '2025-11-06', '2025-05-15',
       '2025-10-09', '2025-10-27', '2025-08-11', '2025-01-28',
       '2025-01-14', '2025-10-13', '2025-02-21', '2025-08-29',
       '2025-05-05', '2025-07-31', '2025-02-07', '2025-09-15',
       '2025-09-22', '2025-03-17', '2025-10-25', '2025-09-24',
       '2025-12-08', '2025-07-01', '2025-04-27', '2025-11-19',
       '2025-07-22', '2025-09-01', '2025-12-01', '2025-10-05',
       '2025-08-26', '2025-09-29', '2025-01-02', '2025-12-05',
       '2025-04-23', '2025-10-16', '2025-04-19', '2025-02-03',
       '2025-08-10', '2025-04-30', '2025-05-30', '2025-09-20',
       '2025-07-19', '2025-10-17', '2025-04-04', '2025-03-30',
       '2025-11-29', '2025-10-18', '2025-08-21', '2025-01-15',
       '2025-01-22', '2025-05-03', '2025-07-17', '2025-05-02',
       '2025-05-29', '2025-09-03', '2025-07-15', '2025-01-12',
       '2025-05-04', '2025-06-04', '2025-01-04', '2025-01-31',
       '2025-03-26', '2025-07-18', '2025-06-27', '2025-08-18',
       '2025-12-21', '2025-05-18', '2025-08-01', '2025-12-14',
       '2025-12-26', '2025-01-25', '2025-01-01', '2025-07-25',
       '2025-03-25', '2025-01-06', '2025-06-30', '2025-03-16',
       '2025-06-16', '2025-07-13', '2025-09-06', '2025-10-03',
       '2025-06-01', '2025-10-31', '2025-02-16', '2025-12-03',
       '2025-06-02', '2025-08-04', '2025-09-16', '2025-03-20',
       '2025-06-05', '2025-01-11', '2025-11-08', '2025-05-11',
       '2025-10-23', '2025-09-02', '2025-08-24', '2025-05-25',
       '2025-01-29', '2025-11-22', '2025-07-14', '2025-06-14',
       '2025-04-02', '2025-02-17', '2025-06-09', '2025-10-02',
       '2025-11-07', '2025-04-09', '2025-11-15', '2025-01-03',
       '2025-11-28', '2025-03-24', '2025-01-18', '2025-11-13',
       '2025-12-10', '2025-09-12', '2025-02-22', '2025-01-05',
       '2025-05-31', '2025-02-15', '2025-10-12', '2025-11-24',
       '2025-05-28', '2025-04-20', '2025-10-08', '2025-07-20',
       '2025-11-02', '2025-06-29', '2025-07-11', '2025-08-22',
       '2025-09-28', '2025-02-24', '2025-12-20', '2025-12-18',
       '2025-04-24', '2025-09-25', '2025-10-06', '2025-02-27',
       '2025-03-22', '2025-06-22', '2025-05-22', '2025-03-23',
       '2025-08-02', '2025-11-25', '2025-08-15', '2025-12-25',
       '2025-07-12', '2025-01-19', '2025-03-02', '2025-06-26',
       '2025-08-31', '2025-04-25', '2025-02-05', '2025-11-03',
       '2025-09-07', '2025-02-02', '2025-06-18', '2025-10-15',
       '2025-05-16', '2025-01-09', '2025-07-28', '2025-08-06',
       '2025-06-23', '2025-12-24', '2025-07-16', '2025-12-09',
       '2025-11-21', '2025-01-08', '2025-03-29', '2025-07-26',
       '2025-08-14', '2025-01-23', '2025-12-11', '2025-03-15',
       '2025-11-04', '2025-01-24', '2025-03-03', '2025-04-12',
       '2025-02-14', '2025-05-20', '2025-08-05', '2025-10-21',
       '2025-07-08', '2025-04-08', '2025-05-27', '2025-09-11',
       '2025-07-24', '2025-03-27', '2025-08-08', '2025-06-19',
       '2025-10-14', '2025-08-17', '2025-12-13', '2025-12-02',
       '2025-11-23', '2025-08-30', '2025-02-08', '2025-04-26',
       '2025-12-06', '2025-12-30', '2025-04-01', '2025-10-22',
       '2025-07-30', '2025-11-05', '2025-01-10', '2025-07-03',
       '2025-03-19', '2025-12-17', '2025-04-13', '2025-02-12',
       '2025-12-31', '2025-11-26', '2025-05-10', '2025-05-14',
       '2025-08-25', '2025-03-18', '2025-07-06', '2025-08-09',
       '2025-11-14', '2025-05-17', '2025-12-22', '2025-03-01',
       '2025-10-28', '2025-04-14', '2025-06-24', '2025-11-17',
       '2025-12-15', '2025-01-13', '2025-12-16', '2025-08-27',
       '2025-10-30', '2025-01-26', '2025-07-10', '2025-06-08',
       '2025-09-09', '2025-03-05', '2025-02-10', '2025-08-03',
       '2025-08-13', '2025-01-17', '2025-09-04', '2025-09-08',
       '2025-11-18', '2025-02-20', '2025-06-07', '2025-09-05',
       '2025-05-13', '2025-04-10', '2025-03-10', '2025-11-09',
       '2025-02-18', '2025-11-27', '2025-09-30', '2025-06-21',
       '2025-01-27', '2025-07-04', '2025-02-04', '2025-11-30',
       '2025-02-23', '2025-03-14', '2025-03-28', '2025-09-13',
       '2025-07-05', '2025-01-30', '2025-08-12', '2025-06-11',
       '2025-07-29', '2025-02-06', '2025-02-01', '2025-06-20',
       '2025-08-07', '2025-03-12', '2025-08-23', '2025-06-13',
       '2025-10-29', '2025-07-09', '2025-03-09', '2025-10-01',
       '2025-02-28', '2025-03-07', '2025-10-24', '2025-05-09',
       '2025-08-19', '2025-07-23', '2025-12-19', '2025-08-28',
       '2025-03-13', '2025-06-28', '2025-11-12', '2025-07-21',
       '2025-09-21', '2025-04-21', '2025-04-18', '2025-12-29',
       '2025-04-28', '2025-02-11', '2025-09-10', '2025-11-01',
       '2025-09-19', '2025-03-11', '2025-07-27', '2025-04-05',
       '2025-04-11', '2025-07-07', '2025-04-16', '2025-03-04',
       '2025-05-07', '2025-10-07', '2025-10-11', '2025-04-07',
       '2025-10-10', '2025-02-29'], dtype=object)