In [5]:
import pandas as pd

df_categoria = pd.read_parquet('../data/bronze/PS_Categoria.parquet')
df_cliente = pd.read_parquet('../data/bronze/PS_Cliente.parquet')
df_conta_pagamento = pd.read_parquet('../data/bronze/PS_Conta_Pagar.parquet')
df_conta_receber = pd.read_parquet('../data/bronze/PS_Conta_Receber.parquet')
df_meta = pd.read_parquet('../data/bronze/PS_Meta2025.parquet')
df_banco_central = pd.read_parquet('../data/bronze/bcb_cotacoes.parquet')

In [17]:
df_categoria.head()

  codigo_categoria                        nome_categoria tipo_categoria
0           1.1.01           VENDA DE PRODUTOS NACIONAIS        receita
1           1.1.02          VENDA DE PRODUTOS EXPORTAÇÃO        RECEITA
2           1.1.03       PRESTAÇÃO DE SERVIÇOS NACIONAIS        Receita
3           1.1.04  PRESTAÇÃO DE SERVIÇOS INTERNACIONAIS        reCeita
4           1.1.05                RECEITA DE ASSINATURAS        REceita

In [20]:
print(df_categoria.info())
print(df_categoria.value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   codigo_categoria  34 non-null     object
 1   nome_categoria    34 non-null     object
 2   tipo_categoria    34 non-null     object
dtypes: object(3)
memory usage: 972.0+ bytes
None
codigo_categoria  nome_categoria                            tipo_categoria
3.1.06            ÁGUA E SANEAMENTO                         despesa           2
1.1.02            VENDA DE PRODUTOS EXPORTAÇÃO              RECEITA           1
1.1.01            VENDA DE PRODUTOS NACIONAIS               receita           1
1.1.04            PRESTAÇÃO DE SERVIÇOS INTERNACIONAIS      reCeita           1
1.1.05            RECEITA DE ASSINATURAS                    REceita           1
1.1.06            RECEITA FINANCEIRA SOBRE APLICAÇÕES       receita           1
1.1.03            PRESTAÇÃO DE SERVIÇOS NACIONAIS           Receita           1
1.1.08            JUROS RECEBIDOS                           ReceitA           1
1.1.09            DIVIDENDOS RECEBIDOS                      receitA           1
1.1.10            RECEITA DE LICENCIAMENTO DE SOFTWARE      RECEita           1
3.1.01            SALÁRIOS E ORDENADOS                      despesa           1
3.1.02            ENCARGOS TRABALHISTAS                     DESPESA           1
3.1.03            IMPOSTOS E TAXAS                          Despesa           1
3.1.04            ALUGUEL E CONDOMÍNIO                      deSpesa           1
1.1.07            VARIAÇÃO CAMBIAL ATIVA                    RECEITA           1
3.1.05            ENERGIA ELÉTRICA                          DESpesa           1
3.1.07            INTERNET E TELECOMUNICAÇÕES               DESPESA           1
3.1.08            MARKETING E PUBLICIDADE                   DespESa           1
3.1.09            DESPESAS BANCÁRIAS INTERNACIONAIS         desPesA           1
3.1.10            TAXAS SOBRE OPERAÇÕES DE CÂMBIO           DESPesa           1
3.1.11            VARIAÇÃO CAMBIAL PASSIVA                  despESA           1
3.1.12            FRETES E LOGÍSTICA INTERNACIONAL          DESPESa           1
3.1.13            SOFTWARE / LICENÇA DE USO                 Despesa           1
3.1.14            CONSULTORIAS E SERVIÇOS TERCEIROS         dEspesa           1
3.1.15            SEGUROS EMPRESARIAIS                      DESpESA           1
3.1.16            MANUTENÇÃO DE SISTEMAS                    desPesa           1
3.1.17            INFRAESTRUTURA EM NUVEM                   DESPesa           1
3.1.18            CUSTOS COM API FINANCEIRA                 DespESa           1
3.1.19            TARIFAS DE TRANSFERÊNCIAS INTERNACIONAIS  despesa           1
3.1.20            PERDAS OPERACIONAIS                       DESPESA           1
3.1.21            OUTRAS DESPESAS OPERACIONAIS              despesa           1
Name: count, dtype: int64

In [14]:
df_cliente.head()

   id_cliente     nome_cliente    pais_cliente data_cadastro_cliente
0           1       Ana Souza           BRASIL            2023-01-05
1           2    CARLOS MENDES       portugal             12/01/2023
2           3   Julien  Martin         FranÃ§a            2023-01-18
3           4  michael johnson  Estados Unidos            25/01/2023
4           5     Sophia Brown         CANADÃ            2023-02-02